#!/bin/bash

BASE=.
DEST=$BASE/root/cdoc

mkdir -p $DEST
mkdir -p $BASE/logs
ln -f chickadee-jquery.js $DEST
ln -f chickadee.css $DEST
ln -f prettify-bundle.js $DEST
# Note: modernizr.respond.js is modernizr.custom.js + respond.min.js.
# Currently, it must be regenerated by hand.
for i in modernizr*js; do
  ln -f "$i" $DEST/
done
ln -f mag.png $DEST
ln -f jquery-*.js $DEST

