name: Test egg
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        chicken-version:
          - 5.3.0
          - 4.13.0    # https://github.com/ursetto/chickadee/issues/3
    runs-on: ${{ matrix.os }}
    name: Test egg
    steps:
      - uses: actions/checkout@v3
      - uses: ursetto/chicken-toolchain@v0
        id: chicken
        with:
          chicken-version: ${{ matrix.chicken-version }}
      - name: "chicken-install -test"
        run: |
          case "${{ steps.chicken.outputs.chicken-version }}" in
            # spiffy-request-vars has an intermittently broken test on chicken-4.x on Linux.
            4.*) chicken-install spiffy-request-vars
                 chicken-install -test ;;
            5.*) chicken-install -test ;;
            *) exit 1 ;;
          esac
