name: Test egg
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        chicken-version:
          - 5.3.0
          - 4.13.0
    runs-on: ${{ matrix.os }}
    name: Test egg
    steps:
      - uses: actions/checkout@v3
      - uses: ursetto/chicken-toolchain@v0
        id: chicken
        with:
          chicken-version: ${{ matrix.chicken-version }}
      - run: chicken-install -test
